"""initial: create projects, blogs, skills, messages tables

Revision ID: 185215da0263
Revises: 
Create Date: 2026-06-15 22:33:54.564150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '185215da0263'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False, comment='Tiêu đề bài viết'),
    sa.Column('slug', sa.String(length=320), nullable=False, comment='URL-friendly — tự generate từ title, dùng trong route /blog/:slug'),
    sa.Column('excerpt', sa.String(length=600), nullable=False, comment='Tóm tắt ngắn hiển thị trên blog listing card'),
    sa.Column('content', sa.Text(), nullable=False, comment='Nội dung đầy đủ dạng Markdown — render bằng react-markdown trên FE'),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True, comment='URL ảnh bìa bài viết'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, comment="Tags phân loại: ['react', 'python', 'tutorial']"),
    sa.Column('category', sa.String(length=100), nullable=True, comment="Category chính: 'Tutorial', 'Deep Dive', 'Career', 'Review'"),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=False, comment='Estimated read time — tự tính từ content (~200 words/min)'),
    sa.Column('meta_title', sa.String(length=70), nullable=True, comment='SEO title — mặc định dùng title nếu để trống'),
    sa.Column('meta_description', sa.String(length=160), nullable=True, comment='SEO meta description — mặc định dùng excerpt nếu để trống'),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='blog_status'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='Pin bài viết lên đầu listing'),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_category'), 'blogs', ['category'], unique=False)
    op.create_index(op.f('ix_blogs_slug'), 'blogs', ['slug'], unique=True)
    op.create_index(op.f('ix_blogs_status'), 'blogs', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Họ tên người gửi'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='Email người gửi — validate format trên Pydantic schema'),
    sa.Column('company', sa.String(length=200), nullable=True, comment='Tên công ty / tổ chức (optional)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Số điện thoại (optional)'),
    sa.Column('subject', sa.String(length=300), nullable=False, comment='Tiêu đề / chủ đề tin nhắn'),
    sa.Column('body', sa.Text(), nullable=False, comment='Nội dung đầy đủ của tin nhắn'),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'REPLIED', 'ARCHIVED', 'SPAM', name='message_status'), nullable=False, comment='Trạng thái xử lý — hiển thị trong admin dashboard'),
    sa.Column('is_starred', sa.Boolean(), nullable=False, comment='Đánh dấu quan trọng trong admin'),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp khi admin reply'),
    sa.Column('reply_note', sa.Text(), nullable=True, comment='Ghi chú nội bộ của admin (không gửi cho người dùng)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP người gửi — dùng để detect spam (IPv6 max 45 chars)'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User-Agent header của request'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_email'), 'messages', ['email'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Tên dự án'),
    sa.Column('slug', sa.String(length=220), nullable=False, comment='URL-friendly identifier, tự generate từ title'),
    sa.Column('summary', sa.String(length=500), nullable=False, comment='Mô tả ngắn hiển thị trên card (≤ 500 ký tự)'),
    sa.Column('description', sa.Text(), nullable=False, comment='Mô tả chi tiết dạng Markdown — hiển thị trên trang detail'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True, comment='URL ảnh thumbnail (Supabase Storage hoặc Cloudinary)'),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True, comment='Danh sách URL ảnh screenshots của dự án'),
    sa.Column('demo_video_url', sa.String(length=500), nullable=True, comment='URL video demo (YouTube, Loom, ...)'),
    sa.Column('github_url', sa.String(length=500), nullable=True, comment='Link GitHub repo'),
    sa.Column('live_url', sa.String(length=500), nullable=True, comment='Link live demo / production'),
    sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=False, comment="Danh sách công nghệ: ['React', 'FastAPI', 'PostgreSQL']"),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True, comment="Tags phân loại: ['fullstack', 'ai', 'mobile']"),
    sa.Column('status', sa.Enum('COMPLETED', 'IN_PROGRESS', 'ARCHIVED', name='project_status'), nullable=False),
    sa.Column('project_type', sa.Enum('PERSONAL', 'TEAM', 'FREELANCE', 'OPEN_SOURCE', name='project_type'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='Hiển thị trên trang Home (featured section)'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='Ẩn/hiện project — False thì chỉ admin mới thấy'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Thứ tự hiển thị — số nhỏ hơn hiện trước'),
    sa.Column('github_stars', sa.Integer(), nullable=True, comment='Số stars GitHub (sync định kỳ)'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='Lượt xem trang detail'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Tên công nghệ: 'React', 'FastAPI', 'PostgreSQL'"),
    sa.Column('category', sa.Enum('FRONTEND', 'BACKEND', 'DATABASE', 'DEVOPS', 'LANGUAGE', 'TOOL', 'AI_ML', 'OTHER', name='skill_category'), nullable=False, comment='Nhóm kỹ năng để group trên trang Skills'),
    sa.Column('proficiency', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiency_level'), nullable=False, comment='Mức độ thành thạo — hiển thị dạng badge trên FE'),
    sa.Column('proficiency_percent', sa.Integer(), nullable=False, comment='Phần trăm thành thạo 0-100 — dùng cho progress bar trên FE'),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='URL icon SVG (devicons, simple-icons) hoặc Supabase Storage'),
    sa.Column('icon_name', sa.String(length=100), nullable=True, comment="Tên icon theo devicons convention: 'react', 'python', 'postgresql'"),
    sa.Column('color', sa.String(length=7), nullable=True, comment="Hex color code brand: '#61DAFB' cho React, '#3776AB' cho Python"),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Thứ tự trong nhóm — số nhỏ hơn hiện trước'),
    sa.Column('years_of_experience', sa.Integer(), nullable=True, comment='Số năm kinh nghiệm với công nghệ này'),
    sa.Column('description', sa.String(length=300), nullable=True, comment='Mô tả ngắn: đã dùng ở đâu, làm gì với công nghệ này'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('proficiency_percent >= 0 AND proficiency_percent <= 100', name='ck_skill_proficiency_percent'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_email'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_blogs_status'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_slug'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_category'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
